# This is a basic workflow to help you get started with Actions

name: FPChange

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Decrypt env
        run: gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.ENV_PASSPHRASE }} --output .env prod.env.gpg

      # Runs a set of commands using the runners shell
      - name: Run script
        run: ./FPCexport.sh
        
      - name: Send mailer
        # You may pin to the exact commit or the version.
        # uses: devellany/send-mail@45dbe31722b9c29635bc9d60315d420218093c56
        uses: devellany/send-mail@v1.0.2
        with:
          # Enter SMTP host.
          host: smtp.neu.edu
          # Enter SMTP port. (defaults to 465)
          port: 25 # optional, default is 465
          # Enter sender name.
          sender: do-not-reply@northeastern.edu
          # Enter sender mail.
          from: do-not-reply@northeastern.edu
          # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
          to: nate.moran@northeastern.edu
          # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
          subject: test
          # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
          body: test
          # Attachment files are entered as an array. Required key 'path'. (The prefix 'file://' if you want to read a file)
          attachments: extract.csv # optional        
      
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v2.2.4
      #   with:
      #     name: LDAPextract.csv
      #     path: extract.csv
      #     retention-days: 30

      # - name: SharePoint uploader
      #   # You may pin to the exact commit or the version.
      #   # uses: su-dont/share-point-uploader@d5219f8801329ec36b7add0d3874a9df0564c577
      #   uses: su-dont/share-point-uploader@v2.1
      #   with:
      #     # SharePoint URL
      #     sp_url: https://northeastern-my.sharepoint.com/:f:/r/personal/nate_moran_northeastern_edu
      #     # SharePoint Username
      #     sp_username: nate.moran@northeastern.edu
      #     # SharePoint Password
      #     sp_password: ${{ secrets.PASSWORD }}
      #     # SharePoint destination folder
      #     sp_folder: "/Documents/Documents/FPC/"
      #     # SharePoint destination file name
      #     sp_file_name: LDAPextract.csv
      #     # File to be uploaded
      #     file: extract.csv
